### ISSUE TITLE
Reduce the number of arguments in DSL methods

### ISSUE THREAD

**Issue by Crunch09** [metaminded/tabulatr2#36]
currently DSL methods each take **20** parameters which doesn't feel right and seems way too much. This makes the code bloated and ugly (e.g. [here](https://github.com/metaminded/tabulatr2/blob/master/lib/tabulatr/renderer/column.rb#L27-L108) and [here](https://github.com/metaminded/tabulatr2/blob/master/lib/tabulatr/data/dsl.rb#L53-L57)). Also our code rating is [not good at all](https://codeclimate.com/github/metaminded/tabulatr2/Tabulatr::Data::DSL) because of it.

So i was thinking which of these params would be dispensable. The current params are:
```
name
header: nil
sort_sql: nil
filter_sql: nil
sql: nil
table_column_options: {}
classes: nil
width: false
align: false
valign: false
wrap: nil
th_html: false
filter_html: false
filter_label: nil
filter: true
sortable: true
format: nil
map: true
cell_style: {}
header_style: {}
```
My suggestion would be to reduce them to
```
name
header: nil
filter: true
sort(able): true
data_html: {}
header_html: {}
```

`name` and `header` are very important and stay for obvious reasons.
`filter` and `sort / sortable` also replace the functionality from `filter_sql` and `sort_sql`. They take a string to set SQL, a symbol to set a different filter type or a boolean to enable or disable it.
`data_html` and `header_html` allow to set html on the data and header cells like [SimpleForm's](https://github.com/plataformatec/simple_form) `input_html` and `label_html`.
`sql` is just a shortcut for `filter_sql` / `sort_sql` so it gets removed.
`table_column_options` was only needed in the pre-keyword-arguments era so it gets removed, too.
`classes`, `width`, `align`, `valign`, `wrap`, `cell_style` and `header_style` are only shortcuts so they get also removed.
`th_html` is replaced by `header_html`.
I couldn't find any usage of `filter_html` within the code so it is also removed.
There is no reason for `filter_label`, instead it should be handled with proper `i18n`.
`format` is only a shortcut for providing a block, so it's dispensable.
It seems like the purpose of `map` could also be handled within the formatting block.

These are obviously big changes but in my opinion we should make them and we should make them before going `1.0`. Any thoughts on this are very welcome!

cc: @no-dashes

**Comment by no-dashes** [comment]
This stuff IS clumsy. /me agrees.

BUT

* `filter_label` was introduced recently, 'cause you may very well want to have a different label in the filter than on the column. Example is a column which is headed by an icon, in the filter dialog, this looks plain stupid.
* `table_column_options` survived, because I didn't want to break the 'old' tabulatr data files. No objection to remove it.
* specifying the same thing for `filter_sql` and `sort_sql` seems inconvenient, so I (still) like the `sql` option.
* I use `width`, `align`, and `wrap` a lot and wouldn't like to see them go, to be honest...

Just my 7ct
