### ISSUE TITLE
Is mongoid support planned?

### ISSUE THREAD

**Issue by sdistefano** [metaminded/tabulatr2#42]
I note that mongoid was supported on tabulatr, but I failed to get tabulatr2 to work with it. Are there plans to support it?

**Comment by no-dashes** [comment]
Hey @sdistefano! tabulatr2 is a complete rewrite, especially the DSL and the searching/filtering/paging stuff has changed fundamentally. Since we didn't need mongo for "our own" stuff, we dropped mongo support for now. That's *not* because we don't *want* to support it, but because we didn't have the time to do so.
So, sadly, there's no mongoid support so far, but if you're willing to contribute, you're highly welcome and we'd love to support your work.

**Comment by Crunch09** [comment]
I'll close this because the question was answered. @sdistefano feel free to ping us if you have any further questions or need any help.
